// Generated by the shya compiler from D:\project\shya\tests\cases\01-core.shya.
// Target: ES2026. Do not edit by hand.

let label = "shya";

function describe(name, times) {
  let out = name;
  for (let i = 0; i < times; i += 1) {
    out = out + "!";
  }
  return out;
}

function main() {
  console.log(describe(label, 3));
  console.log(100 + 100, 50);
  console.log(3.141592653589793, 1, 10, 1.3862943611198906);
  console.log(0.03490658503988659, 1.8378770664093453, 1.4142135623730951);
  console.log("chained:", 1 < 2 && 2 < 3);
  if (1 < 2 && 2 < 3) {
    console.log("chained comparison ok");
  } else if (false) {
  } else {
    console.log("impossible");
  }
  switch (label) {
    case "shya":
    case "noname":
      console.log("matched");
      break;
    case "other":
      // fallthrough
    default:
      console.log("default");
      break;
  }
  let arr = [3, 1, 4, 1, 5];
  console.log(arr.length);
  console.log(arr.slice(1, 3).indexOf(4));
  console.log(arr[0]);
  for (let i = 0; i < arr.length; i += 2) {
    console.log("even index", i);
  }
  let bag = { x: 1, y: 2 };
  console.log(Object.keys(bag), Object.values(bag), Object.entries(bag));
  let m = new Map();
  let st = new Set();
  console.log(m.size, st.size, label.length);
  let s = `k=${1 + 1}`;
  console.log(s);
  let n = 0;
  while (n < 3) {
    n++;
  }
  console.log("n =", n);
  console.log(Math.trunc(9 / 2), Math.ceil(9 / 2), Math.floor(9 / 2), Math.round(9 / 2), 2 ** 10, 7 % 3);
  console.log(undefined, typeof 1 === "number", Array.isArray(arr), typeof label === "string");
}

main();
