// Generated by the shya compiler from D:\project\shya\tests\cases\02-macros.shya.
// Target: ES2026. Do not edit by hand.

function makePlayer(name) {
  return ({
    name: name,
    hp: 4,
    seat: 1,
    judge: () => ({ getSuit: () => "red" }),
    nextSeat: () => makePlayer("p2"),
    recover: (n) => { console.log("recover " + n); },
    draw: (n) => { console.log("draw " + n); },
    say: (m) => { console.log("say " + m); return { say: (x) => console.log("say " + x) }; }
  });
}
function main() {
  let d = makePlayer("a");
  d?.say("hello")?.say("nice");
  let player = makePlayer("p");
  const _p = player.nextSeat();
  _p.recover(2);
  _p.draw(2);
  const _q = player.nextSeat();
  _q?.recover(2);
  _q?.draw(2);
  let card = player.judge();
  switch (card.getSuit()) {
    case "red":
      {
        console.log("红");
      }
      break;
    case "black":
      {
        console.log("黑");
      }
      break;
    case "none":
      {
        console.log("无色");
      }
      break;
  }
  card = player.judge();
  switch (card.getSuit()) {
    case "red":
      console.log("R");
      break;
    case "black":
      console.log("B");
      break;
    case "none":
      console.log("N");
      break;
  }
  console.log("---");
  {
    console.log("no target needed");
  }
  let p2 = makePlayer("q");
  console.log("who=" + p2.name);
  {
    console.log("named a");
  }
}
main();
