// Generated by the shya compiler from D:\project\shya\tests\cases\07-misc.shya.
// Target: ES2026. Do not edit by hand.

const VERSION = "1.0";
function greet(name, greeting = "你好") {
  return `${greeting}，${name}！`;
}
function rest(first, ...others) {
  let total = first;
  for (const v of others) {
    total = total + v;
  }
  return total;
}
async function fetchHp() {
  await new Promise((resolve) => setTimeout(resolve, 1));
  return 42;
}
function risky(flag) {
  try {
    if (flag) {
      throw new Error("boom");
    }
    return "ok";
  } catch (e) {
    return "caught: " + e.message;
  } finally {
    console.log("finally");
  }
}
function main() {
  console.log(greet("世界"));
  console.log(greet("shya", "hi"));
  console.log(rest(1, 2, 3, 4));
  let arr = [1, 2, 3];
  let copy = [...arr, 4];
  console.log(copy.length, Object.values(copy));
  console.log(VERSION);
  let obj = { a: 1, b: 2 };
  for (const [k, v] of Object.entries(obj)) {
    console.log(k, v);
  }
  for (const k of Object.keys(obj)) {
    console.log("key", k);
  }
  console.log(risky(true));
  console.log(risky(false));
  for (let i = 3; i > 0; i += -1) {
    console.log("down", i);
  }
  {
    const __shya_seq = Array.from(arr);
    for (let __shya_i = 1; __shya_i < 3; __shya_i += 1) {
      const v = __shya_seq[__shya_i];
      console.log("slice", v);
    }
  }
  let maybe = null;
  console.log(maybe?.getHp());
  console.log(maybe?.(1));
}
main();
