// Generated by the shya compiler from D:\project\shya\tests\cases\10-typeops.shya.
// Target: ES2026. Do not edit by hand.

function probe(x) {
  console.log(Array.isArray(x), !(Array.isArray(x)));
  console.log(x === undefined, !(x === undefined));
  console.log(x instanceof Date, !(x instanceof Date));
  console.log(!(typeof 3 === "string"), !(typeof 3 === "number"));
  console.log(1 < 2 && 2 < 3, 3 > 2 && 2 > 1, 1 < 2 && 2 > 3);
}

function main() {
  probe([1, 2]);
  probe(undefined);
  probe("s");
}

main();
