// Generated by the shya compiler from D:\project\shya\tests\cases\14-declare.shya.
// Target: ES2026. Do not edit by hand.

function hostRandom(max) { return Math.floor(max / 2); };
function hostLog(msg) { console.log("[host] " + msg); };
function makeCard(suit, rank) { return { suit: suit, rank: rank }; };
function makePlayer(name) {
  return {
    name: name,
    hp: 4,
    hand: [makeCard("red", 7), makeCard("black", 9)],
    judge: () => makeCard("red", 1),
    recover: (n) => { console.log("recover " + n); },
    draw: (n = 1) => { console.log("draw " + n); },
    say: (m) => { console.log("say " + m); return makePlayer("other"); },
  };
};

function main() {
  let p = makePlayer("me");
  let opp = makePlayer("you");
  console.log(p.name, p.hp);
  console.log("手牌数", p.hand.length);
  let c = p.judge();
  console.log(c.suit, c.rank);
  p.recover(2);
  p.draw();
  p.say("hi").say("there");
  console.log("hostRandom", hostRandom(6));
  hostLog("done");
  for (const card of p.hand) {
    console.log("card", card.suit, card.rank);
  }
  let players = [p, opp];
  for (const who of players) {
    console.log(who.name, who.hp);
  }
}

main();
